import 'package:hive/hive.dart';

part 'comic_models.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
enum ComicFormat {
  @HiveField(0)
  cbz,
  @HiveField(1)
  zip,
  @HiveField(2)
  cbr,
  @HiveField(3)
  rar,
  @HiveField(4)
  pdf,
  @HiveField(5)
  folder,
  @HiveField(6)
  image,
}

@HiveType(typeId: 1)
class ComicChapter extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String seriesKey;

  @HiveField(2)
  final String seriesTitle;

  @HiveField(3)
  final String chapterTitle;

  @HiveField(4)
  final String originalFilename;

  @HiveField(5)
  final String sourceRelativePath;

  @HiveField(6)
  final ComicFormat format;

  @HiveField(7)
  final DateTime importedAt;

  @HiveField(8)
  final DateTime? modifiedAt;

  @HiveField(9)
  final double? issueNumber;

  @HiveField(10)
  final int? pageCount;

  ComicChapter({
    required this.id,
    required this.seriesKey,
    required this.seriesTitle,
    required this.chapterTitle,
    required this.originalFilename,
    required this.sourceRelativePath,
    required this.format,
    required this.importedAt,
    this.modifiedAt,
    this.issueNumber,
    this.pageCount,
  });

  String get issueLabel {
    if (issueNumber == null) return chapterTitle;
    return '#${issueNumber!.toStringAsFixed(1)}';
  }

  String get subtitle {
    List<String> parts = [format.name.toUpperCase()];
    if (pageCount != null) parts.add('$pageCount pages');
    return parts.join(' • ');
  }
}

@HiveType(typeId: 2)
class ComicProgress extends HiveObject {
  @HiveField(0)
  int pageIndex;

  @HiveField(1)
  DateTime lastReadAt;

  ComicProgress({this.pageIndex = 0, required this.lastReadAt});
}

class ComicSeries {
  final String key;
  final String title;
  final List<ComicChapter> chapters;

  ComicSeries({required this.key, required this.title, required this.chapters});
}

